//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMusical_shop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokupateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokupateli()
        {
            this.Korzina_pokupateley = new HashSet<Korzina_pokupateley>();
            this.Pridajis = new HashSet<Pridaji>();
        }
    
        public int id_pokupatelya { get; set; }
        public string familiya { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<decimal> telefon { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina_pokupateley> Korzina_pokupateley { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pridaji> Pridajis { get; set; }
    }
}
