//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMusical_shop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pridaji
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pridaji()
        {
            this.Korzinas = new HashSet<Korzina>();
        }
    
        public int id_prodaji { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> stoimost { get; set; }
        public Nullable<int> id_sotrudnika { get; set; }
        public Nullable<int> id_clienta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina> Korzinas { get; set; }
        public virtual Pokupateli Pokupateli { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
